export const SET_USER = 'SET_USER';
export const LOGOUT = "LOGOUT";
export const CLEAR_DATA = "CLEAR_DATA"

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';






export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";
export const AUTHENTICATED = "AUTHENTICATED";
