export const SET_USER = 'SET_USER';
export const LOGOUT = "LOGOUT";
export const CLEAR_DATA = "CLEAR_DATA"

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const CREATE_ITEM = 'CREATE_ITEM';
export const FETCH_ITEM = 'FETCH_ITEM';
export const FETCH_ITEMS = 'FETCH_ITEMS';
export const DELETE_ITEM = 'DELETE_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';

export const CREATE_LOG = 'CREATE_LOG';
export const FETCH_LOG = 'FETCH_LOG';
export const FETCH_LOGS = 'FETCH_LOGS';
export const DELETE_LOG = 'DELETE_LOG';
export const EDIT_LOG = 'EDIT_LOG';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';

export const FETCH_PAST_DUE = 'FETCH_PAST_DUE';

export const SELECT_ITEM = 'SELECT_ITEM';
export const UPDATE_SELECTED_ITEM_ON_CAT_EDIT = 'UPDATE_SELECTED_ITEM_ON_CAT_EDIT';
export const SELECT_CATEGORY_ID ='SELECT_CATEGORY_ID';
export const SELECT_ITEM_FOR_EDITED_CATEGORY = 'SELECT_ITEM_FOR_EDITED_CATEGORY';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SELECT_LOG = 'SELECT_LOG';

export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";
export const AUTHENTICATED = "AUTHENTICATED";
